#!/bin/bash

PROJECT_ROOT="/mnt/d/Projects/DataEngineeringLab"
DOCKER_DIR="$PROJECT_ROOT/docker/postgres"

# Load Docker environment variables
set -a
source "$DOCKER_DIR/.env"
set +a

COMPOSE_FILE="docker-compose.yml"